Samples:
  sample1:
    R1Fastq: fastq/SRR11901822_1.fastq.gz
    R2Fastq: fastq/SRR11901822_2.fastq.gz
    comparisonGroup: '1'
    id: SRR11901822
    specie: Metamycoplasma hominis
    username: '1'
  sample2:
    R1Fastq: fastq/SRR11901823_1.fastq.gz
    R2Fastq: fastq/SRR11901823_2.fastq.gz
    comparisonGroup: '1'
    id: SRR11901823
    specie: Metamycoplasma hominis
    username: '1'
  sample3:
    R1Fastq: fastq/SRR11901824_1.fastq.gz
    R2Fastq: fastq/SRR11901824_2.fastq.gz
    comparisonGroup: '1'
    id: SRR11901824
    specie: Metamycoplasma hominis
    username: '1'
  sample4:
    R1Fastq: fastq/SRR11901825_1.fastq.gz
    R2Fastq: fastq/SRR11901825_2.fastq.gz
    comparisonGroup: '1'
    id: SRR11901825
    specie: Metamycoplasma hominis
    username: '1'
__use_yte__: true
