Samples:
  sample1:
    R1Fastq: fastq/SRR11901822_1.fastq.gz
    R2Fastq: fastq/SRR11901822_2.fastq.gz
    comparison group: '1'
    id: SRR11901822
    specie: Mycoplasma hominis
    user name: '1'
__use_yte__: true
